services:
  # This service runs your Django + Gunicorn application
  web:
    # Use your ECR image URL here
    image: 715227882366.dkr.ecr.ap-south-1.amazonaws.com/onlinejudge:latest
    command: gunicorn --bind 0.0.0.0:8000 OnlineJudge.wsgi:application
    volumes:
      - static_volume:/algop_oj/staticfiles
    env_file:
      - .env

  # This service runs the Nginx web server
  nginx:
    image: nginx:latest
    ports:
      - "80:80"   # Maps the server's public port 80 to this container's port 80
      - "443:443" # Add this port for HTTPS
    volumes:
      # Link the Nginx configuration file
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # Shares the static files directory with the Nginx container
      - static_volume:/algop_oj/staticfiles:ro
      # Https configuration
      - ./certbot/www:/var/www/certbot/:ro
      - /etc/letsencrypt/:/etc/letsencrypt/:ro

    depends_on:
      - web # Ensure Nginx starts after the web service(Django application)

# Defines the shared volume for static files
volumes:
  static_volume: