# Generated by Django 4.2.23 on 2025-08-14 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the language version(e.g., C++17, Python 3.9)', max_length=50, unique=True)),
                ('extension', models.SlugField(help_text='The file extension for this language (e.g., py, cpp)', unique=True)),
                ('command', models.CharField(help_text='The command to execute the code. Use {source} and {executable} as placeholders.', max_length=255)),
            ],
            options={
                'verbose_name': 'Programming Language',
                'verbose_name_plural': 'Programming Languages',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionkey', models.CharField(blank=True, help_text='The UUID key ', max_length=100)),
                ('title', models.CharField(help_text='The title of the problem.', max_length=255)),
                ('description', models.TextField(help_text='A detailed description of the problem, including input/output format.')),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=10)),
                ('time_limit', models.FloatField(default=1.0, help_text='Time limit in seconds for a solution to run.')),
                ('memory_limit', models.IntegerField(default=256, help_text='Memory limit in megabytes (MB).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_problems', to='authentication.user_registrations')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(help_text='The input for this test case.')),
                ('expected_output', models.TextField(help_text='The expected output for this test case.')),
                ('is_sample', models.BooleanField(default=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problems.questions')),
            ],
            options={
                'verbose_name': 'Test Case',
                'verbose_name_plural': 'Test Cases',
            },
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filekey', models.CharField(blank=True, help_text='The UUID key for code/input/output files.', max_length=100)),
                ('runtime', models.FloatField(blank=True, help_text='Execution time in seconds.', null=True)),
                ('memory_used', models.IntegerField(blank=True, help_text='Memory used in megabytes (MB).', null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Accepted', 'Accepted'), ('Wrong Answer', 'Wrong Answer'), ('Time Limit Exceeded', 'Time Limit Exceeded'), ('Syntax Error', 'Syntax Error'), ('Indentation Error', 'Indentation Error'), ('Value Error', 'Value Error'), ('Name Error', 'Name Error'), ('Type Error', 'Type Error'), ('Compilation Error', 'Compilation Error'), ('Runtime Error', 'Runtime Error'), ('Memory Limit Exceeded', 'Memory Limit Exceeded'), ('System Error', 'System Error')], default='Pending', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(help_text='Language of the submission', on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='problems.languages')),
                ('problem', models.ForeignKey(help_text='Problem Title', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='authentication.user_registrations')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
