# Generated by Django 4.2.23 on 2025-08-15 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submissions',
        ),
    ]
