# Generated by Django 4.2.23 on 2025-09-11 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filekey",
                    models.CharField(
                        blank=True,
                        help_text="The UUID key for code/input/output files.",
                        max_length=100,
                    ),
                ),
                (
                    "runtime",
                    models.FloatField(
                        blank=True, help_text="Execution time in seconds.", null=True
                    ),
                ),
                (
                    "memory_used",
                    models.IntegerField(
                        blank=True,
                        help_text="Memory used in megabytes (MB).",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Wrong Answer", "Wrong Answer"),
                            ("Time Limit Exceeded", "Time Limit Exceeded"),
                            ("Syntax Error", "Syntax Error"),
                            ("Indentation Error", "Indentation Error"),
                            ("Value Error", "Value Error"),
                            ("Name Error", "Name Error"),
                            ("Type Error", "Type Error"),
                            ("Compilation Error", "Compilation Error"),
                            ("Runtime Error", "Runtime Error"),
                            ("System Error", "System Error"),
                        ],
                        default="Pending",
                        max_length=30,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("output_log", models.TextField(blank=True, null=True)),
                (
                    "language",
                    models.ForeignKey(
                        help_text="Language of the submission",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="problems.languages",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        help_text="Problem Title",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="problems.questions",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission",
                "verbose_name_plural": "Submissions",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
