# Generated by Django 4.2.23 on 2025-08-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='output_log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
