# Generated by Django 4.2.23 on 2025-09-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_alter_submissions_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Wrong Answer', 'Wrong Answer'), ('Time Limit Exceeded', 'Time Limit Exceeded'), ('Syntax Error', 'Syntax Error'), ('Indentation Error', 'Indentation Error'), ('Value Error', 'Value Error'), ('Name Error', 'Name Error'), ('Type Error', 'Type Error'), ('Compilation Error', 'Compilation Error'), ('Runtime Error', 'Runtime Error'), ('System Error', 'System Error')], default='Pending', max_length=30),
        ),
    ]
