# Generated by Django 4.2.23 on 2025-09-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address for OTP verification', max_length=254)),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('password_reset', 'Password Reset'), ('password_change', 'Password Change')], help_text='Purpose of OTP', max_length=20)),
                ('otp', models.CharField(help_text='6-digit OTP code', max_length=6)),
                ('temp_data', models.JSONField(blank=True, default=dict, help_text='Temporary data storage')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether OTP has been verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='OTP creation time')),
                ('expires_at', models.DateTimeField(help_text='OTP expiration time')),
            ],
            options={
                'verbose_name': 'OTP Verification',
                'verbose_name_plural': 'OTP Verifications',
                'db_table': 'Auth_Otp',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'purpose', 'is_verified', '-created_at'], name='Auth_Otp_email_11440e_idx')],
            },
        ),
    ]
