# Generated by Django 4.2.23 on 2025-08-01 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_registrations',
            name='confirm_password',
        ),
    ]
