# Generated by Django 4.2.23 on 2025-08-30 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_alter_questions_author'),
        ('submissions', '0003_alter_submissions_user'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_registrations',
        ),
    ]
